version: "3"
services:
 postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgres"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=C0l0mb14++
      - POSTGRES_DATABASE=store
    container_name: postgres-db

volumes:
  postgres-data:
